// apps.js

export const apps = {
  system: {
    id: 'system',
    name: 'System',
    type: 'app',
    icon: '💻',
    accessLevel: 1,
    showOnDesktop: true,
    jsFiles: ['system.js'],
    cssFiles: ['system.css'],
  },
  trash: {
    id: 'trash',
    name: 'Trash',
    type: 'folder',
    icon: '🗑️',
    accessLevel: 1,
    showOnDesktop: true,
    jsFiles: ['trash.js'],
    cssFiles: ['trash.css'],
    subApps: [],
  },
  documents: {
    id: 'documents',
    name: 'Documents',
    type: 'folder',
    icon: '📁',
    accessLevel: 1,
    showOnDesktop: true,
    jsFiles: ['documents.js'],
    cssFiles: ['documents.css'],
    subApps: ['cookieBatchLog', 'placeholder'],
  },
  cookieBatchLog: {
    id: 'cookieBatchLog',
    name: 'Cookie Batch Log',
    type: 'app',
    icon: '🍪',
    accessLevel: 1,
    showOnDesktop: false,
    jsFiles: ['cookieBatchLog.js'],
    cssFiles: ['cookieBatchLog.css'],
  },
  cookieDeliveryMap: {
    id: 'cookieDeliveryMap',
    name: 'Cookie Delivery',
    type: 'map',
    icon: '🍪',
    accessLevel: 1,
    showOnDesktop: false,
    jsFiles: ['cookieDeliveryMap.js'],
    cssFiles: ['cookieDeliveryMap.css'],
  },
  encryption: {
    id: 'encryption',
    name: 'Encryption',
    type: 'app',
    icon: '🔒',
    accessLevel: 1,
    showOnDesktop: true,
    jsFiles: ['encryption.js'],
    cssFiles: ['encryption.css'],
  },
  lemonList: {
    id: 'lemonList',
    name: 'Lemon List',
    type: 'app',
    icon: '🍋',
    accessLevel: 1,
    showOnDesktop: true,
    jsFiles: ['lemonList.js'],
    cssFiles: ['lemonList.css'],
  },
  maps: {
    id: 'maps',
    name: 'Maps',
    type: 'folder',
    icon: '🗺️',
    accessLevel: 1,
    showOnDesktop: true,
    jsFiles: ['maps.js'],
    cssFiles: ['maps.css'],
    subApps: ['cookieDeliveryMap', 'undergroundMap'],
  },
  placeholder: {
    id: 'placeholder',
    name: 'Placeholder',
    type: 'app',
    icon: '📄',
    accessLevel: 1,
    showOnDesktop: false,
    jsFiles: ['placeholder.js'],
    cssFiles: ['placeholder.css'],
  },
  propaganda: {
    id: 'propaganda',
    name: 'Propaganda',
    type: 'app',
    icon: '🏛️',
    accessLevel: 1,
    showOnDesktop: true,
    jsFiles: ['propaganda.js'],
    cssFiles: ['propaganda.css'],
  },
  undergroundMap: {
    id: 'undergroundMap',
    name: 'Underground',
    type: 'map',
    icon: '🐀',
    accessLevel: 1,
    showOnDesktop: false,
    jsFiles: ['undergroundMap.js'],
    cssFiles: ['undergroundMap.css'],
  },
};

/*     Alibi: {
      name: 'Alibi',
      type: 'app',
      icon: '㊙️',
      accessLevel: 1,
      showOnDesktop: true,
      jsFiles: ['propaganda.js'],
      cssFiles: ['propaganda.css'],
    },
    GeoQuesting: {
      name: 'GeoQuesting',
      type: 'app',
      icon: '🧭',
      accessLevel: 1,
      showOnDesktop: true,
      jsFiles: ['propaganda.js'],
      cssFiles: ['propaganda.css'],
    },
    Cookbook: {
      name: 'Cookbook',
      type: 'app',
      icon: '📖',
      accessLevel: 1,
      showOnDesktop: true,
      jsFiles: ['propaganda.js'],
      cssFiles: ['propaganda.css'],
    }, */
/*     Gossip: {
      name: 'Gossip',
      type: 'app',
      icon: '👄',
      accessLevel: 1,
      showOnDesktop: true,
      jsFiles: ['propaganda.js'],
      cssFiles: ['propaganda.css'],
    },
    QDaddy: {
      name: 'QDaddy',
      type: 'app',
      icon: '🚄',
      accessLevel: 1,
      showOnDesktop: true,
      jsFiles: ['propaganda.js'],
      cssFiles: ['propaganda.css'],
    },
    Stocks: {
      name: 'Stocks',
      type: 'app',
      icon: '🚀',
      accessLevel: 1,
      showOnDesktop: true,
      jsFiles: ['propaganda.js'],
      cssFiles: ['propaganda.css'],
    }, */

export const getAppById = (id) => Object.values(apps).find(app => app.id === id);