name: Update Announcements File

on:
  issues:
    types: [opened]

jobs:
  update-announcements:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'new-announcement')
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Debug information
      run: |
        echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
        cat $GITHUB_EVENT_PATH

    - name: Update announcements file
      run: |
        python .github/scripts/update_announcements.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add data/announcements.json
        git commit -m "Update announcements from new issue" || exit 0
        git push
